name = "chhagoldhara-high-school-site"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "SCHOOL_KV"
id = "524ca99d527645ecbbc34be595401736"
